// import humps from 'humps'
import sampleSize from 'lodash/sampleSize';
import random from 'lodash/random';

const INTERESTS = [
  'basketball',
  'football',
  'volleyball',
  'marathon_running',
  'skiing',
  'tennis',
  'cycling',
  'swimming',
  'baseball',
  'mountain_climbing',
  'chess',
  'playing_a_musical_instrument',
  'reading',
  'writing',
  'sketching',
  'photography',
  'design',
  'painting',
  'boardgames',
  'creating_and_organizing_a_book_club',
  'networking_events',
  'local_meetups',
  'volunteering_at_a_charity_center',
  'public_speaking',
  'exploring_other_cultures',
  'dancing',
  'camping',
  'language_classes',
  'archery',
  'gardening',
  'stand_up_comedy',
  'baking',
  'journaling',
  'calligraphy',
  'fencing',
  'theater',
  'yoga',
  'languages',
];
const CARS = [
  'honda',
  'acura',
  'peugeot',
  'citroen',
  'benz',
  'mitsu',
  'jeep',
  'dodge',
  'maybach',
  'daimlerchrysler',
  'smart',
  'bentley',
  'Lamborghini',
  'audi',
  'Volkswagen',
  'skoda',
  'seat',
  'bugatti',
  'fiat',
  'ferrari',
  'alfaromeo',
  'maserati',
  'lancia',
  'toyota',
  'lexus',
  'scion',
  'daihatsu',
  'renault',
  'infiniti',
  'nissan',
  'hummer',
  'pontiac',
  'buick',
  'chevrolet',
  'cadillac',
  'suzuki',
  'opel',
  'saab',
  'subaru',
  'saturn',
  'holden',
  'daewoo',
  'rover',
  'volvo',
  'ford',
  'astonmartin',
  'mazda',
  'lincoln',
  'landrover',
  'jaguar',
  'mercury',
];

const getCars = () => sampleSize(CARS, random(0, 2));
const getInterests = () => sampleSize(INTERESTS, random(0, 10));

export { getInterests, getCars };
